### ISSUE TITLE
PlayerPrefixChangeEvent - NullPointerException

### ISSUE THREAD

**Issue by TheOfficialDuck** [homuradev/RPNames#1]
```accesslog
17.06 21:28:25 [Server] ERROR Could not pass event PlayerPrefixChangeEvent to RPNames v0.1.6.2-SNAPSHOT
17.06 21:28:25 [Server] INFO org.bukkit.event.EventException: null
17.06 21:28:25 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at cc.co.homuradev.rpnames.MainClass$1.run(MainClass.java:254) ~[?:?]
17.06 21:28:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
17.06 21:28:25 [Server] INFO Caused by: java.lang.NullPointerException
17.06 21:28:25 [Server] INFO at cc.co.homuradev.rpnames.api.User.match(User.java:130) ~[?:?]
17.06 21:28:25 [Server] INFO at cc.co.homuradev.rpnames.api.User.changeName(User.java:101) ~[?:?]
17.06 21:28:25 [Server] INFO at cc.co.homuradev.rpnames.events.MainListener.onPrefixChange(MainListener.java:67) ~[?:?]
17.06 21:28:25 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor455.execute(Unknown Source) ~[?:?]
17.06 21:28:25 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1594]
17.06 21:28:25 [Server] INFO ... 11 more
```

This is the stack trace.

**Comment by homuradev** [comment]
Tested and added some more checks for the sync.
